title = "Plurigrid"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = "At Plurigrid we aim to build a neutral energy coordination layer that can ultimately scale to _all_ communities ✨☄️"

[extra]
github = "https://github.com/plurigrid"
twitter = "https://twitter.com/plurigrid"

date_style = "%B %e, %Y"
